---
- name: Update web servers
  hosts: webservers
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Write the apache config file
    ansible.builtin.template:
      src: /configs/index.j2
      dest: /var/www/html/index.php
    - name: Apply Page Template
  - name: ensure apache is running
    ansible.builtin.service:
      name: httpd
      state: started

