---
- name: Update load balancer
  hosts: nginx
  remote_user: root

  tasks:
  - name: Ensure nginx is at the latest version
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: Write the apache config file
    ansible.builtin.template:
      src: /configs/nginxconf.j2
      dest: /etc/nginx/nginx.conf
  - name: Ensure nginx is running
    ansible.builtin.service:
      name: nginx
      state: started